sequenceDiagram

Worker->>Customer: HTTP POST

Customer-->>Worker: HTTP 500

Worker->>Retry: Retry Request

Retry->>Worker: Retry

Worker->>Customer: HTTP POST

Customer-->>Worker: Timeout

Worker->>Retry: Retry

Retry->>DLQ: Max Retry Exceeded